### ISSUE TITLE
AspectRatioFrameLayout ClassCastException 

### ISSUE THREAD

**Issue by oahmedazab** [kaltura/playkit-android-ima#103]
I am trying to integrate IMAPlugin but i get this exception

>         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: myapp.easycast.demo, PID: 21621
                         E  java.lang.RuntimeException: Unable to start activity ComponentInfo{myappi.PlayerActivity}: java.lang.ClassCastExcept
                            ion: com.google.android.exoplayer2.ui.AspectRatioFrameLayout cannot be cast to com.kaltura.android.exoplayer2.ui.AspectRatioFrameLayout
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
                         E      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6626)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
                         E  Caused by: java.lang.ClassCastException: com.google.android.exoplayer2.ui.AspectRatioFrameLayout cannot be cast to com.kaltura.android.exoplayer2.ui.AspectRatioFrameLayout
                         E      at com.kaltura.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:414)
                         E      at com.kaltura.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:336)
                         E      at com.kaltura.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:332)
                         E      at com.kaltura.playkit.plugins.ima.ExoPlayerWithAdPlayback.init(ExoPlayerWithAdPlayback.java:155)
                         E      at com.kaltura.playkit.plugins.ima.ExoPlayerWithAdPlayback.<init>(ExoPlayerWithAdPlayback.java:141)
                         E      at com.kaltura.playkit.plugins.ima.IMAPlugin.onLoad(IMAPlugin.java:183)
                         E      at com.kaltura.playkit.PlayerLoader.loadPlugin(PlayerLoader.java:204)
                         E      at com.kaltura.playkit.PlayerLoader.load(PlayerLoader.java:77)
                         E      at com.kaltura.playkit.PlayKitManager.loadPlayer(PlayKitManager.java:65)
                         E      at com.kaltura.playkit.PlayKitManager.loadPlayer(PlayKitManager.java:71)
                         E      a myapp.player.kaltura.PlayerKalturaImpl.<init>(PlayerKalturaImpl.kt:43)
                         E      at myapp.player.PlayerActivity.onCreate(PlayerActivity.kt:67)
                         E      at android.app.Activity.performCreate(Activity.java:7032)
                         E      at android.app.Activity.performCreate(Activity.java:7023)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
                         E      ... 9 more

**Comment by kaltura-hooks** [comment]
Hi @oahmedazab,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by oahmedazab** [comment]
any update?

**Comment by oahmedazab** [comment]
@giladna can you help me with this issue?
Thanks

**Comment by oahmedazab** [comment]
i think maybe the reason is that i am using exoplayer too in my application

kexoplayer
https://github.com/kaltura/kexoplayer-android/blob/master/lib/src/main/res/layout/exo_simple_player_view.xml

exoplayer
https://github.com/google/ExoPlayer/blob/8ec4aad001667674da679f37136bf986ab0e8493/library/ui/src/main/res/layout/exo_simple_player_view.xml

maybe the resource merger takes exoplayer's xml file

**Comment by giladna** [comment]
@oahmedazab 

which version are you using?

**Comment by giladna** [comment]
please attach the grade you are using

**Comment by giladna** [comment]
please use com.kaltura.android.exoplayer2.ui.PlayerView for playing with our player
```
<com.kaltura.android.exoplayer2.ui.PlayerView
            android:id="@+id/player_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_above="@+id/controls_container"/>
```

**Comment by oahmedazab** [comment]
@giladna 
> which version are you using?

i tired using versions 4.5.0 and 4.8.0


> please attach the grade you are using

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'


android {
    defaultConfig {
        minSdkVersion 18
        compileSdkVersion android_compile_sdk_version
        targetSdkVersion android_target_sdk_version
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    androidExtensions {
        experimental = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation project(':app_core')
    implementation project(':dialog')

    // Support libraries
    implementation "androidx.appcompat:appcompat:$appcompat_version"
    implementation "androidx.constraintlayout:constraintlayout:$constraintlayout_version"
    implementation "androidx.mediarouter:mediarouter:$mediarouter_version"
    implementation "androidx.legacy:legacy-support-v4:$legacy_support_v4_version"

    implementation "com.google.android.material:material:$material_version"

    // Rx
    implementation "io.reactivex.rxjava2:rxandroid:$rxAndroid_version"
    implementation "io.reactivex.rxjava2:rxjava:$rxJava_version"

    // Exoplayer
    implementation "com.google.android.exoplayer:exoplayer:$exoplayer_version"
    // implementation "com.google.android.exoplayer:extension-ima:$exoplayer_version"

    // Kaltura
    implementation "com.kaltura.playkit:playkit:$kaltura_version"
    implementation "com.kaltura.playkit:imaplugin:$kaltura_version"
    implementation "com.kaltura.playkit:playkitproviders:$kaltura_version"
    implementation "com.kaltura.playkit:kavaplugin:$kaltura_version"
    api "com.kaltura.playkit:googlecast:$kaltura_version"

    // Glide
    implementation "com.github.bumptech.glide:glide:$glide_version"
    kapt "com.github.bumptech.glide:compiler:$glide_version"

    // Timber
    implementation "com.jakewharton.timber:timber:$timber_version"
}

```


> please use com.kaltura.android.exoplayer2.ui.PlayerView for playing with our player

as i can see from the stacktrace somehow when ExoPlayerWithAdPlayback creates its PlayerView it inflates the view from wrong xml file

PlayView creation
https://github.com/kaltura/playkit-android-ima/blob/develop/imaplugin/src/main/java/com/kaltura/playkit/plugins/ima/ExoPlayerWithAdPlayback.java#L155

AspectRatioFrameLayout 
https://github.com/kaltura/kexoplayer-android/blob/master/lib/src/main/java/com/kaltura/android/exoplayer2/ui/PlayerView.java#L389

xml file
https://github.com/kaltura/kexoplayer-android/blob/404a65059386b7fc7a2e50d0860cd0ede54761c8/lib/src/main/res/layout/exo_simple_player_view.xml

**Comment by giladna** [comment]
@oahmedazab 

I can understand the reason for this same id used.
lf you change the order in the gradle would it help or it causes other issues?

```
    // Kaltura
    implementation "com.kaltura.playkit:playkit:$kaltura_version"
    implementation "com.kaltura.playkit:imaplugin:$kaltura_version"
    implementation "com.kaltura.playkit:playkitproviders:$kaltura_version"
    implementation "com.kaltura.playkit:kavaplugin:$kaltura_version"
    api "com.kaltura.playkit:googlecast:$kaltura_version"

    // Exoplayer
    implementation "com.google.android.exoplayer:exoplayer:$exoplayer_version"
    // implementation "com.google.android.exoplayer:extension-ima:$exoplayer_version"

**Comment by oahmedazab** [comment]
Surprisingly it worked!!
thank you so much for you help @giladna

**Comment by oahmedazab** [comment]
well i am re-opening this issue again because later i discovered that switching dependencies order will case the same error  for me when i try to use ExoPlayer

i guess we should have better solution for this
right now i can only use KalturaPlayer or ExoPlater

**Comment by giladna** [comment]
@oahmedazab 

why dont you use playkit only?

you can play direct urls with playkit as well

**Comment by oahmedazab** [comment]
Yes i know that playkit can play direct urls as well
but for some use-cases w just want use different custom player with different features

**Comment by giladna** [comment]
@oahmedazab can you add some more information about these use cases maybe we can add it as well

**Comment by giladna** [comment]
@oahmedazab 

fixed for 
   def exoPlayerVersion = '2.11.7'
    api "com.kaltura.playkit:kexoplayer:$exoPlayerVersion"
